---
title: 'Writing Reproducible Scientific Papers in R: A Tutorial Series'
author: Nick Fox
date: '2018-08-16'
slug: writing-reproducible-scientific-papers-in-r-a-tutorial-series
categories: []
tags:
  - R
  - RMarkdown
  - Papaja
  - tutorial
  - publication
---

I just preprinted my first 1st-author paper. Exciting! You can find it here: <a href="https://psyarxiv.com/3v7hx/" target="_blank">How Many Psychologists Use Questionable Research Practices?</a>
I used this paper as a project to learn how to create a fully reproducible paper.  By that, I mean a person could take my data files and my "paper" file and fully reproduce the paper (including analyses, figures, tables, etc) and the final document all in one step.  The special part of this process is the "paper" file.  I used R, RStudio, RMarkdown, and a package called Papaja (Aust & Barth 2016) to create a file that contains text, analyses, and figure creation all in one place.  There are no image files or pre-made tables...the whole process of data analysis, figure/table creation, and manuscript preperation happens in the same place at the same time.

I originally was going to write a set of blog posts about the process, but felt it was much more natural to <b>show</b> rather than <b>tell</b>, so I started a YouTube video series walking through all the steps!  
You can find the playlist of videos on my YouTube page here: <a href="https://www.youtube.com/watch?v=MxCnnqpnN5Y&list=PLmvNihjFsoM5hpQdqoI7onL4oXDSQ0ym8" target="_blank">Writing Reproducible Scientific Papers in R</a>

I will be making 1-2 videos per week as we journey from download programs all the way through writing completely reproducible scientific papers.  You can do it! It just takes a little bit of practice to get comfortable with all of the steps involved, and I hope I can help with that!


