---
title: 'My Long, Strange Trip Through Graduate School'
author: Nick Fox
date: '2019-04-10'
slug: trip-through-grad-school
categories: []
tags:
  - graduate school
  - PhD
  - Masters
  - first-generation college student
  - drop out
---

It took me 10 years to go from an undergraduate degree in Biochemistry to a PhD in Social Psychology.  Along the way I dropped out of a PhD program, worked as a lab manager, re-applied and re-entered graduate school, changed PhD advisors, and changed sub-disciplines of study.  There are many ways to be successful in graduate school.  If your goal is to most fully complete your education by earning your PhD, you can do it – even if you hit some bumps!  

This is how I managed to do it:

I'm a first-generation college student.  Back in 2005 when I was entering college as an undergraduate, I didn't think much of it, but looking back on it 14 years later, I think it shaped a lot of what was to come.  I started off as a psychology major, and I HATED IT.  I found the classes boring, the professors uninteresting, and the material unimportant.  Stony Brook University required that all students take a couple of classes across a broad range of topics - arts, humanities, "physical sciences" and "social sciences".  In the course of doing these required courses, I fell in love with Biology and Chemistry.  By my junior year, I had decided to change majors from Psychology to Biology with a Chemistry minor.  I soon found out that Stony Brook didn't offer a minor in Chemistry, so I decided to major in Biochemistry instead.  Not so different, right? WRONG.

While Biochemistry wasn't quite what I was expecting (3 semesters of calculus and a semester of physical chemistry? yuck), the department encouraged its students to become research assistants in the labs on campus.  I printed out what must have been a laughable CV and went to the absolutely packed research faire.  I met a researcher named Anne Savitt who worked on the bacteria Francisella tularensis, the causative agent of tularemia, and I asked to leave my CV materials with her for consideration.  She asked me to sit down and interviewed me on the spot. This was very intimidating as I 1) had never heard of tularemia before and 2) was recovering from a semi-major surgery that week.  She emailed me later that week and asked me to join her lab, where I worked for the final two years of my time at Stony Brook.

In the Savitt lab, we were trying to purify and identify a target bacterial protein, p32, which bound to the human receptor of the globular region of the complement protein C1q (gC1qR).  This was my first taste of research in immunology, and I really liked it.  For some reason, this extremely infectious bacteria (yes, the US government considered it for biological warfare) had a protein that bound a very specific receptor that regulated the innate immune system.  Why would that be?  This was the question that drove my work for two years...and I couldn't answer it.  It was a very realistic taste of academic research.

At this point, it was the Fall of 2008 and the economy was taking a nosedive.  The job prospects for a 21-year-old with an undergraduate degree in Biochemistry weren't looking great.  At the time, graduate school sounded like the perfect solution: keep my undergraduate student loans in forbearance, guaranteed 5 years of income, and free school!  I applied to six cell biology/immunology programs.  I was interviewed at the University of Texas at Austin and the University of Arizona in Tucson.  I received an offer from both programs and accepted the offer from UA.  Part of this was due to my girlfriend Mariana’s parents living in Tucson (now my in-laws, hello Katia and Verne!) but most of it was due to the great program focused on Immunobiology.  I entered the program in Fall 2009.

While at UA I rotated through three labs, as is customary in many biomedical research fields.  I worked with Dr. Felicia Goodrum, who’s lab focused on how the Human Cytomegalovirus (HCMV) avoided detection from the host immune system.  I then worked with Dr. Maggie So, who’s lab focused on how Neisseria gonorrhoeae latched onto host epithelial cells using their pilli.  My final rotation was with Dr. Janko Nicolich-Zugich, who worked on the aging human immune system (among many other things).  I asked to join Janko’s lab after my first year at UA and he agreed to be my PhD advisor.  I started working on describing the immune cells of the elderly– specifically, how their cells responded to being activated compared to immune cells from younger adults. 

This was really great work, though there was a family health issue that came up that made it hard for me to be halfway across the country.  I made the -=extremely=- difficult decision to drop out of the PhD program at UA.  I told my advisor the situation and he was very supportive.  I was now 2 years through the five year program and was planning to complete my comprehensive exams.  If I was able to complete them, I would be able to “master out” of the program with a master’s degree in Immunobiology.  Unfortunately for me, the comprehensive exams were being revamped that year and required substantively more time to complete – more time than I had left in Tucson.  I wound up leaving the program without getting my master’s degree and moved back to the east coast.

I moved in with Mariana who was living in New York City working towards her PhD in Public Health.  Luckily, Janko had a collaborator in New York who was looking for a lab manager.  I was able to land an interview with Dr. Raphael Clynes for a lab manager position in his hematopathology lab at Columbia University Medical Center.  It actually took several months to get hired and be put on payroll at Columbia, and between July and October of 2012 I was unemployed living in New York City.  Mariana and I were living in a 5th floor walk-up studio apartment on the salary of one graduate student stipend.  We decided to start a business to try and make enough extra money to survive.  We called it Nooch Fiber, and we dyed yarn in our kitchen and sold it on Etsy to make ends meet.  Flash-forward 7 years and we are now partners in our LLC selling direct to customers and wholesale to local yarn shops…a happy side project that came out of some serious hardship.

Being a lab manager with Raf was a great experience – although there is no upward mobility as a lab manager, it is a great opportunity to learn about the business of research.  I managed two NIH R01 grants, purchased and managed a research animal colony, and worked on a collaboration with the Mayo Clinic.  While there, I worked on generating a procedure to test how the immune system of breast cancer patients responded to the bioactive anti-cancer drug Tratuzumab.  That work was recently published here:

I knew I wanted to go back to graduate school, but common knowledge said that dropping out of a graduate program put a black mark on your record.  Shortly after starting my job at Columbia, I applied to a number of graduate programs in Immunology.  I was rejected at each school.  I worked for a year and applied again the following fall.  Over the year, I read up on the relationship between the immune system and the brain – a growing field called Psychoneuroimmunology.  I focused my applications on psychology programs that had professors working on this area of research.

I was accepted into the psychology program at Rutgers to work with Dr. Alex Kusnecov.  While I was in his lab, my work focused on the role of the maternal immune system in the neurodevelopment of offspring.  I was specifically interested in how adaptive immune system activation affected spatial learning in adult offspring in mice.  This was really interesting work that was the basis of an NIH R21 grant in the lab.  However, after finishing my master’s work on this topic, I felt it was best for my progress in the program to change academic advisors.  It was the end of 2015 and there was a growing movement in Psychology focused on academic best practices and replicability, and I felt that I could really thrive by focusing my work on this relatively new topic of metascience.

Now, 2.5 years into my PhD program at Rutgers, I moved from the sub-field of behavioral neuroscience to social psychology.  Up until this time, I had only taken a few undergraduate psychology courses, and a few graduate courses focused on neuroscience…none in social psychology.  I asked Dr. Lee Jussim if he would be willing to take me as a student, and he offered me a 6 month “trial” to see how we worked together.  I spent most of that time working on a project to measure the use of questionable research practices in the fields of Sociology and Chemistry.  I came in particularly useful in this project as I had some background in chemistry.  After 6 months, we both felt like we could work together, and I transitioned into his lab permanently in the summer of 2016 – 3 years after starting my PhD.

The idea of working with Lee was a little nerve-wracking.  I knew of his reputation as being a “rabble rouser” (a title he wears with pride) and that some of his work had been on controversial topics in social psychology such as stereotype accuracy.  I was asked by graduate students at other schools; “are you sure you want to be associated with this kind of scientist?” and the truth was, I wasn’t sure.  I knew that I would be focusing my work on how researchers conducted research, and I promised myself that I would try to stay as uncontroversial as possible.  Of course, metascience has a level of controversy baked into it, so I could only avoid so much.

I am very glad Lee agreed to take me on as ascending 4th year graduate student, as his type of mentorship really worked for my work style.  I had several research topics I wanted to work on, and Lee gave me the freedom to success or fail.  He was the first to admit that he wasn’t an expert in some of the things I wanted to work on, but that he would support me finding those experts and getting my work done.  That worked really well for me.  I also think my interested rubbed off on the lab a little bit – Lee jointed Twitter (IT WAS MY FAULT EVERYBODY AND I’M SORRY!) and the Jussim lab veered more and more into being a lab on the metascience map (at least that’s my interpretation).

Today was the official academic end of this journey – I deposited my dissertation with the Graduate School at Rutgers and it was accepted.  The email from the school was really meaningful to me: “ALL degree requirements have been approved and you will receive your degree.  NOTHING FURTHER IS NEEDED”. I nearly started to cry when that email came through today.  I already have a post-PhD job as well.  I started working at the Center for Open Science in February, and this last stretch of the dissertation was done as my “second job” once my day job ended.

The NSF GRFP award notifications went out this week, and while some will have received award letters (CONGRATULATIONS!!!), many other great graduate students will have gotten that rejection notice.  I got mine twice – the first for not having enough experience, and the second for having too much experience and not enough publications.  It feels terrible.  But I hope my personal journey through graduate school serves as enough of an example that not only do you not need to win awards or grants, but you can make a lot of mistakes and wind up being a successful scientist in the end.
  
Was it fun all the time? HECK NO! 
Was it fun most of the time, YES!

Remember that graduate school is school, and it is just one part of your life.  Your family is important, as are your romantic partners, your pets, your hobbies, and your sleep (your sleep is very important).  Take it all in stride and keep your eye on that prize and sooner or later (in my case quite a few years later) you can call yourself a doctor, change your business cards, and start correcting people when they call your “Mr.” – for the first couple of weeks until the shine wears off, at least!



